import requests

def Get_duke_urls_descriptions():
  # Original website list and corresponding descriptions (some duplicate URLs have been removed)
  websites = [
      "https://duke.edu/",
      "https://www.duke.edu/about/",
      "https://news.duke.edu/",
      "https://events.duke.edu/",
      "https://careers.duke.edu/",
      "https://dukeconnect.duke.edu/",
      "https://admissions.duke.edu/",
      "https://graduate.duke.edu/",
      "https://alumni.duke.edu/",
      "https://execed.duke.edu/",
      "https://law.duke.edu/",
      "https://medschool.duke.edu/",
      "https://nursing.duke.edu/",
      "https://business.duke.edu/",
      "https://divinity.duke.edu/",
      "https://pratt.duke.edu/",  # 如果该网站依然有效
      "https://library.duke.edu/",
      "https://research.duke.edu/",
      "https://sustainability.duke.edu/",
      "https://dukeglobalhealth.org/",
      "https://brain.duke.edu/",
      "https://cancer.dukehealth.org/",
      "https://nicholasschool.duke.edu/",
      "https://nasher.duke.edu/",
      "https://duke.press/",
      "https://ip.duke.edu/",
      "https://dukeinnovation.duke.edu/",
      "https://dukespace.duke.edu/",
      "https://dukeconservancy.duke.edu/",
      "https://studentaffairs.duke.edu/",
      "https://dukeathletics.duke.edu/",
      "https://dukechronicle.com/",
      "https://chapel.duke.edu/",
      "https://campusministry.duke.edu/",
      "https://studentgov.duke.edu/",
      "https://ctl.duke.edu/",
      "https://diversity.duke.edu/",
      "https://dukeinternational.duke.edu/",
      "https://dukesummer.duke.edu/",
      "https://dukecontinuinged.duke.edu/",
      "https://dukeresearchers.duke.edu/",
      "https://duke.edu/innovation/",
      "https://it.duke.edu/",
      "https://online.duke.edu/",
      "https://extension.duke.edu/",
      "https://hr.duke.edu/",
      "https://finance.duke.edu/",
      "https://president.duke.edu/",
      "https://communications.duke.edu/",
      "https://healthinnovation.duke.edu/",
      "https://globalhealth.duke.edu/",  # 与 dukeglobalhealth.org 区分开来
      "https://datascience.duke.edu/",
      "https://entrepreneurship.duke.edu/",
      "https://researchoffice.duke.edu/",
      "https://clinicalresearch.duke.edu/",
      "https://dukehealth.org/",
      "https://www.dukeupress.edu/",
      "https://www.dukehealth.org/locations/duke-university-hospital",  # 专门页面
      "https://rehab.dukehealth.org/",
      "https://transportation.duke.edu/",
      "https://facilities.duke.edu/",
      "https://parking.duke.edu/",
      "https://housing.duke.edu/",
      "https://studyabroad.duke.edu/",
      "https://arts.duke.edu/",
      "https://innovate.duke.edu/",
      "https://community.duke.edu/",
      "https://biology.duke.edu/",
      "https://chemistry.duke.edu/",
      "https://physics.duke.edu/",
      "https://math.duke.edu/",
      "https://cs.duke.edu/",
      "https://english.duke.edu/",
      "https://history.duke.edu/",
      "https://politicalscience.duke.edu/",
      "https://econ.duke.edu/",
      "https://psych.duke.edu/",
      "https://geography.duke.edu/",
      "https://anthropology.duke.edu/",
      "https://art.duke.edu/",
      "https://music.duke.edu/",
      "https://philosophy.duke.edu/",
      "https://religiousstudies.duke.edu/",
      "https://environment.duke.edu/",
      "https://languages.duke.edu/",
      "https://film.duke.edu/",
      "https://drama.duke.edu/",
      "https://comparativeliterature.duke.edu/",
      "https://neuroscience.duke.edu/",
      "https://stats.duke.edu/",
      "https://computerengineering.duke.edu/",
      "https://ece.duke.edu/",
      "https://me.duke.edu/",
      "https://bme.duke.edu/",
      "https://che.duke.edu/",
      "https://digital.duke.edu/",
      "https://financialaid.duke.edu/"
  ]


  # Corresponding English descriptions list
  descriptions = [
      "Duke University official website providing comprehensive information on academics, research, campus life, and more.",
      "About Duke University, offering details on its background, mission, leadership, and strategic vision.",
      "Campus news platform featuring announcements, research breakthroughs, and community news.",
      "Event calendar listing academic lectures, cultural activities, presentations, and campus events.",
      "Portal for campus recruitment, career development, and employee services.",
      "Portal for internal communication and collaboration within the Duke community.",
      "Undergraduate admissions website with application info, campus tours, and student profiles.",
      "Graduate admissions website offering program details and application guidelines.",
      "Portal for Duke alumni featuring news, events, and networking resources.",
      "Executive education website offering leadership development programs for senior management and professionals.",
      "Duke Law School official website showcasing admissions information, faculty, and legal research.",
      "Duke School of Medicine website covering curricula, research initiatives, and clinical training details.",
      "Duke School of Nursing website featuring program details, research activities, and clinical partnerships.",
      "Duke Fuqua School of Business website presenting business programs, executive education, and research outputs.",
      "Duke Divinity School website covering theological studies, campus ministry, and academic programs.",
      "Duke Pratt-related engineering project website (if active).",
      "Duke University Libraries website offering digital collections, research databases, and library services.",
      "Portal showcasing Duke's research projects, grants, publications, and innovation news.",
      "Platform providing information on Duke's sustainability and green campus initiatives.",
      "Duke Global Health Institute website sharing research on global health challenges and policy initiatives.",
      "Website dedicated to brain science research, neuroscience education, and interdisciplinary programs.",
      "Duke Cancer Institute website detailing patient care services, clinical trials, and cancer research.",
      "Nicholas School of the Environment website focusing on environmental research, sustainability, and policy-making.",
      "Nasher Museum of Art website featuring exhibitions, collections, and cultural programs.",
      "Duke University Press website offering academic books, journals, and scholarly publications.",
      "Portal for Duke's intellectual property and technology transfer resources.",
      "Portal spotlighting innovation and entrepreneurship, highlighting new technologies and startup ventures at Duke.",
      "Provides research computing, IT support, and digital workspace resources for the Duke community.",
      "Website managing Duke's archives, historical documents, and preservation of campus heritage.",
      "Website dedicated to student life services including housing, dining, and campus activities.",
      "Duke Athletics website showcasing sports team schedules, player profiles, and game results.",
      "Independent student-run news outlet covering campus news and opinions.",
      "Duke Chapel website providing information on worship services, concerts, and special events.",
      "Campus Ministry website offering details on spiritual life, worship services, and community outreach programs.",
      "Duke Student Government website offering information on student representation, elections, and initiatives.",
      "Center for Teaching and Learning website with resources for pedagogy and instructional innovation.",
      "Office of Diversity and Inclusion website showcasing campus inclusivity initiatives.",
      "Duke International website featuring information on international exchange, study abroad, and global partnerships.",
      "Duke Summer Session website providing details on short-term courses and summer programs.",
      "Duke Continuing Education website offering professional development and non-degree courses.",
      "Portal for Duke researchers to connect, showcasing interdisciplinary research projects and collaborations.",
      "Showcases innovation projects and cutting-edge research emerging from Duke University.",
      "Duke Information Technology services portal providing IT support and digital resources.",
      "Online Learning portal featuring digital courses, distance education programs, and virtual classrooms.",
      "Website for continuing education and community courses, offering certificate programs to nontraditional students.",
      "Duke Human Resources website featuring employment, benefits, and staff services.",
      "Duke Financial Services portal explaining budgeting, procurement, and fiscal management.",
      "Office of the President's website featuring presidential messages, strategic vision, and leadership news.",
      "Duke Communications website offering media resources, press releases, and branding guidelines.",
      "Center focused on healthcare innovation and technology-driven medical solutions.",
      "Global health policy and collaboration platform, distinct from dukeglobalhealth.org.",
      "Duke Data Science Institute website integrating big data, analytics, and computational research.",
      "Portal supporting entrepreneurial education and startup incubation.",
      "Office platform providing tools, policies, and support services for Duke researchers.",
      "Website dedicated to coordinating clinical trials and translational research.",
      "Official homepage of Duke University Health System, offering information on hospitals and clinics.",
      "Duke University Press website publishing academic monographs and research publications.",
      "Dedicated page showcasing Duke University Hospital's services, patient information, and specialty centers.",
      "Duke Rehabilitation Hospital website detailing rehabilitative care and therapy services.",
      "Campus Transportation website providing details on transit, parking services, and transportation policies.",
      "Duke Facilities Management website featuring campus building maintenance and infrastructure planning information.",
      "Dedicated campus parking services portal offering permit information, maps, and parking regulations.",
      "Duke Housing website offering information on on-campus residence halls and student accommodations.",
      "Study Abroad website offering information on international study programs and exchange opportunities.",
      "Website highlighting Duke campus arts initiatives, exhibitions, and cultural events.",
      "Portal focused on campus innovation projects and entrepreneurial activities.",
      "Website dedicated to Duke's community engagement and service-learning initiatives.",
      "Duke Biology department website featuring teaching and research in the biological sciences.",
      "Duke Chemistry department website showcasing chemical research and educational programs.",
      "Duke Physics department website presenting academic programs, research projects, and lecture series.",
      "Duke Mathematics department website featuring course listings and research directions.",
      "Duke Computer Science department website focused on computing research and information technology.",
      "Duke English department website offering literature, creative writing, and critical theory details.",
      "Duke History department website showcasing academic programs and historical research achievements.",
      "Duke Political Science department website offering course information, lecture series, and research projects.",
      "Duke Economics department website presenting course details and research initiatives.",
      "Duke Psychology department website featuring research labs, course information, and faculty profiles.",
      "Duke Geography department website focusing on interdisciplinary spatial studies and teaching.",
      "Duke Anthropology department website focusing on cultural studies and anthropological research.",
      "Duke Art department website showcasing art, art history, and visual studies programs.",
      "Duke Music department website offering performance details, course info, and concert schedules.",
      "Duke Philosophy department website showcasing philosophy courses, research, and academic activities.",
      "Duke Religious Studies department website providing information on diverse religious traditions and courses.",
      "Duke Environmental Studies department website focusing on interdisciplinary environmental research.",
      "Duke Modern Languages and Cultures department website offering language learning and cross-cultural exchange details.",
      "Duke Film and Media Studies department website presenting film screenings, seminars, and media theory research.",
      "Duke Drama department website featuring theater production, performance, and workshop details.",
      "Duke Comparative Literature department website focusing on global literary comparison and analysis.",
      "Duke Neuroscience website showcasing research on brain function and neural mechanisms.",
      "Duke Statistical Science department website providing information on statistical education and research.",
      "Duke Computer Engineering project website focused on computer engineering education.",
      "Duke Electrical and Computer Engineering department website showcasing research, academic programs, and lab facilities.",
      "Duke Mechanical Engineering department website (if independently maintained) featuring research and design projects.",
      "Duke Biomedical Engineering department website focusing on engineering principles and medical innovation.",
      "Duke Chemical Engineering department website focusing on process engineering, materials, and applied research.",
      "Duke Digital Projects website showcasing digital scholarship and multimedia resources.",
      "Duke Financial Aid website providing information on scholarships, grants, and financial assistance."
  ]


  # Check if URLs are accessible (HTTP status code 200 means accessible)
  duke_websites = []
  duke_descriptions = []

  for url, desc in zip(websites, descriptions):
      try:
          # Use GET request to check status code 
          # HEAD request could be faster but some sites don't support it
          response = requests.get(url, timeout=10)
          if response.status_code == 200:
              duke_websites.append(url)
              duke_descriptions.append(desc)
          else:
              print(f"[Inaccessible] {url} Status code: {response.status_code}")
      except Exception as e:
          print(f"[Error accessing] {url} Error message: {e}")

  # Output results (only returning the accessible sites)
  print("Accessible URL list:")
  print(duke_websites)
  print("\nCorresponding description list:")
  print(duke_descriptions)


  aipi_urls = [
      "https://masters.pratt.duke.edu/ai/",
      "https://masters.pratt.duke.edu/",
      "https://pratt.duke.edu/",
      "https://online.duke.edu/program/artificial-intelligence-for-product-innovation-master-of-engineering/",
      "https://masters.pratt.duke.edu/programs/",
      "https://masters.pratt.duke.edu/industry/ai-affiliates/",
      "https://ai.meng.duke.edu/degree",
      "https://pratt.duke.edu/admissions/masters/",
      "https://pratt.duke.edu/academics/masters/degrees/",
      "https://prattprofessional.bulletins.duke.edu/",
      "https://en.wikipedia.org/wiki/Pratt_School_of_Engineering",
      "https://www.duke.edu/",
      "https://online.duke.edu/",
      "https://dukeapplications.duke.edu/",
      "https://gradschool.duke.edu/",
      "https://library.duke.edu/",
      "https://news.duke.edu/",
      "https://today.duke.edu/",
      "https://dukechronicle.com/",
      "https://www.dukehealth.org/",
      "https://faculty.duke.edu/",
      "https://research.duke.edu/",
      "https://nursing.duke.edu/",
      "https://medschool.duke.edu/",
      "https://www.fuqua.duke.edu/",
      "https://law.duke.edu/",
      "https://sanford.duke.edu/",
      "https://nicholasschool.duke.edu/",
      "https://pratt.duke.edu/research/",
      "https://pratt.duke.edu/people/",
      "https://pratt.duke.edu/events/",
      "https://pratt.duke.edu/news/",
      "https://gradschool.duke.edu/academics/degree-programs",
      "https://dukeengage.duke.edu/",
      "https://curriculum.duke.edu/",
      "https://registrar.duke.edu/",
      "https://alumni.duke.edu/",
      "https://giving.duke.edu/",
      "https://duke-experience.duke.edu/",
      "https://catalog.duke.edu/",
      "https://dukemagazine.duke.edu/",
      "https://innovation.duke.edu/",
      "https://research.duke.edu/centers/",
      "https://global.duke.edu/",
      "https://international.duke.edu/",
      "https://arts.duke.edu/",
      "https://diversity.duke.edu/",
      "https://studentaffairs.duke.edu/",
      "https://careers.duke.edu/",
      "https://it.duke.edu/",
      "https://security.duke.edu/",
      "https://sustainability.duke.edu/",
      "https://centers.duke.edu/",
      "https://outreach.duke.edu/",
      "https://dukeathletics.com/",
      "https://recruit.duke.edu/",
      "https://researchfunding.duke.edu/",
      "https://grants.duke.edu/",
      "https://innovation.duke.edu/startups",
      "https://demographics.duke.edu/",
      "https://spatial.duke.edu/",
      "https://tech.duke.edu/",
      "https://data.duke.edu/",
      "https://ai.duke.edu/",
      "https://dukeinnovation.net/",
      "https://entrepreneurship.duke.edu/",
      "https://socialgood.duke.edu/",
      "https://climate.duke.edu/",
      "https://energy.duke.edu/",
      "https://healthinnovation.duke.edu/",
      "https://medicine.duke.edu/",
      "https://clinicaltrials.duke.edu/",
      "https://labs.duke.edu/",
      "https://pratt.duke.edu/academics/undergraduate/",
      "https://pratt.duke.edu/academics/graduate/",
      "https://pratt.duke.edu/careers/",
      "https://pratt.duke.edu/locations/",
      "https://pratt.duke.edu/faculty/",
      "https://pratt.duke.edu/alumni/",
      "https://pratt.duke.edu/giving/",
      "https://pratt.duke.edu/news-events/",
      "https://pratt.duke.edu/our-impact/",
      "https://pratt.duke.edu/innovation/",
      "https://pratt.duke.edu/collaborations/",
      "https://masters.pratt.duke.edu/ai/certificate/",
      "https://masters.pratt.duke.edu/ai/courses/",
      "https://masters.pratt.duke.edu/ai/degree/",
      "https://masters.pratt.duke.edu/ai/outcomes/",
      "https://masters.pratt.duke.edu/ai/overview/",
      "https://pratt.duke.edu/admissions/",
      "https://pratt.duke.edu/academics/",
      "https://continuingeducation.duke.edu/",
      "https://execed.duke.edu/",
      "https://professional.duke.edu/",
      "https://dukeinnovation.org/",
      "https://dukeexchange.duke.edu/"
  ]

  aipi_descriptions = [
      "The official homepage for Duke's Master of Engineering in Artificial Intelligence for Product Innovation program, with details on curriculum, degree options, admissions, and student resources.",
      "The general portal for Duke Pratt School of Engineering's master's programs, listing all advanced degree offerings and providing an overview of Duke's graduate engineering education.",
      "The main website for Duke's Pratt School of Engineering, offering comprehensive information on academic departments, research initiatives, faculty, and campus life.",
      "A dedicated page for the online option of Duke's Master of Engineering in Artificial Intelligence for Product Innovation, detailing the flexible online curriculum and admissions criteria for working professionals.",
      "A section listing all master's degree programs at Duke Pratt School of Engineering, complete with program structures, elective options, and interdisciplinary opportunities.",
      "A page describing Duke's Data Science and AI Industry Affiliates initiative, where industry partners collaborate with Duke to co-develop curriculum and offer real-world project opportunities.",
      "A specialized subdomain that provides detailed degree information for Duke's AI for Product Innovation Master of Engineering program, including requirements and application procedures.",
      "The admissions portal for Duke Pratt School of Engineering's master's programs, offering guidance on application processes, requirements, deadlines, and financial aid options.",
      "An overview page dedicated to the various master's degree options available at Duke Pratt School of Engineering, enabling prospective students to compare program formats and opportunities.",
      "The official bulletin site for Duke's Pratt professional programs, containing academic bulletins, program summaries, and detailed policy information for graduate degrees.",
      "The Wikipedia page for Pratt School of Engineering, offering an encyclopedic overview of its history, academic programs, research achievements, and contributions.",
      "The official Duke University homepage, providing comprehensive information about Duke's academics, research, news, events, and campus life.",
      "Duke University's online learning portal, offering information on remote and flexible programs including the online Master of Engineering in AI for Product Innovation.",
      "Duke's centralized application portal, where prospective students can submit their applications for various Duke programs.",
      "The Duke Graduate School website, featuring information on degree programs, research opportunities, and general graduate life at Duke.",
      "The Duke University Libraries website, which offers access to a vast digital and physical collection of academic resources.",
      "The official Duke News website, where the latest research, campus news, and announcements from Duke University are published.",
      "Duke Today provides news, features, and updates directly from Duke University, highlighting achievements and campus events.",
      "The Duke Chronicle is the independent student-run newspaper at Duke University, covering campus news and opinion pieces.",
      "The Duke Health website offers comprehensive information on clinical care, research, and education at Duke University Health System.",
      "The Duke Faculty directory, a comprehensive resource that lists Duke faculty members across all disciplines.",
      "Duke's research website showcases major research initiatives, centers, and publications from Duke University.",
      "The Duke School of Nursing website, which provides information on academic programs, research, and clinical practice in nursing.",
      "The Duke School of Medicine website, detailing academic programs, research initiatives, and clinical education in medicine.",
      "The Duke Fuqua School of Business website, which highlights business education, research, and executive programs at Duke.",
      "The Duke University School of Law website, providing information on legal education, research, and career resources.",
      "The Duke Sanford School of Public Policy website, offering details on policy research, academic programs, and public service initiatives.",
      "The Duke Nicholas School of the Environment website, showcasing interdisciplinary environmental research and academic programs.",
      "The Pratt research page provides insights into cutting-edge engineering research, projects, and innovations at Duke's Pratt School of Engineering.",
      "A directory of faculty and staff at Pratt School of Engineering, highlighting profiles, research interests, and contact information.",
      "An events page for Pratt School of Engineering, listing conferences, seminars, and special events hosted by the school.",
      "A news page that features the latest announcements, research breakthroughs, and achievements at Pratt School of Engineering.",
      "A detailed directory of graduate programs offered at Duke, including degree requirements and curriculum information.",
      "Duke Engage is a platform for experiential learning and community-based projects for Duke students.",
      "The Duke curriculum catalog provides detailed course descriptions, program requirements, and academic policies.",
      "The Duke Registrar's website offers information on academic records, enrollment, and course registration policies.",
      "The Duke Alumni website connects former students with news, events, and networking opportunities at Duke.",
      "The Duke Giving website provides information on donation opportunities, fundraising campaigns, and alumni support initiatives.",
      "The Duke Experience website offers insights into campus life, student events, and extracurricular opportunities at Duke.",
      "The Duke University course catalog, which lists course offerings, degree requirements, and academic program details.",
      "Duke Magazine is the official magazine of Duke University, featuring stories on research, innovation, and campus culture.",
      "The Duke Innovation website highlights entrepreneurial initiatives, research commercialization, and startup support at Duke.",
      "A directory of Duke research centers and institutes, showcasing collaborative research and innovation projects.",
      "The Duke Global website features international initiatives, global research, and study abroad opportunities.",
      "The Duke International website promotes cross-cultural exchange and international academic programs at Duke.",
      "The Duke Arts website provides information on arts, cultural events, and creative initiatives at Duke University.",
      "The Duke Diversity website offers resources and programs aimed at fostering inclusion and equity on campus.",
      "Duke Student Affairs provides comprehensive support and services for student life and engagement.",
      "The Duke Career Services website offers resources, workshops, and job listings to help Duke students and alumni advance their careers.",
      "Duke IT Services supports the technology needs of Duke University's students, faculty, and staff.",
      "Duke Security provides information on campus safety, emergency protocols, and security services.",
      "The Duke Sustainability website showcases Duke's commitment to sustainable practices, research, and community initiatives.",
      "A central directory of Duke research centers, facilitating access to interdisciplinary research initiatives.",
      "The Duke Outreach website connects Duke with the local community through service projects and engagement initiatives.",
      "The Duke Athletics website offers news, schedules, and information on Duke University's sports teams and athletic events.",
      "The Duke Recruitment website provides resources and information for prospective employees and new hires at Duke.",
      "A portal for Duke research funding opportunities, grant information, and sponsored research initiatives.",
      "A grants office website where Duke researchers can find information on funding, proposals, and award management.",
      "A page dedicated to Duke's startup initiatives and entrepreneurial projects fostered through innovation programs.",
      "A Duke website focusing on demographic research, data analysis, and studies related to population trends.",
      "A site dedicated to spatial data science and geographic information systems research at Duke.",
      "A portal showcasing technology innovation initiatives at Duke University.",
      "The Duke Data website, a hub for data science research, projects, and academic resources at Duke.",
      "A dedicated Duke Artificial Intelligence site that highlights AI research, applications, and collaborations at Duke.",
      "An alternate Duke Innovation website focusing on technological advancements and entrepreneurial initiatives.",
      "The Duke Entrepreneurship Center provides resources, mentorship, and programs for budding entrepreneurs.",
      "The Duke Social Good lab highlights research and initiatives aimed at leveraging technology for social impact.",
      "The Duke Climate Initiative website is dedicated to interdisciplinary research and policy on climate change.",
      "A site highlighting Duke's energy research and innovation initiatives in collaboration with industry partners.",
      "The Duke Health Innovation website showcases innovative solutions in healthcare research and clinical practice.",
      "The Duke Medicine website features clinical education, research, and advancements in medical science.",
      "A portal for Duke Clinical Trials, offering information on research studies, participation criteria, and trial results.",
      "A directory of Duke research laboratories and facilities across various disciplines.",
      "The undergraduate engineering page at Pratt provides information on Bachelor of Science programs and academic opportunities.",
      "The graduate engineering page at Pratt highlights advanced degree programs, research, and career outcomes for graduate students.",
      "A dedicated page for career services and job placement support specifically for Pratt School of Engineering students.",
      "A location page for Pratt School of Engineering that provides campus maps, facility details, and directions.",
      "A faculty directory page for Pratt School of Engineering, offering detailed profiles and contact information.",
      "A page dedicated to Pratt School of Engineering alumni, highlighting success stories and networking opportunities.",
      "A giving page for Pratt School of Engineering, explaining donation opportunities and support for the school's initiatives.",
      "A combined news and events page for Pratt School of Engineering, keeping visitors updated on the latest happenings.",
      "A page describing the impact and achievements of Pratt School of Engineering in research, innovation, and community engagement.",
      "A dedicated Pratt page that highlights innovation initiatives and emerging technologies within the school.",
      "A page outlining collaborations and partnerships between Pratt School of Engineering and industry or academic institutions.",
      "The Duke AI & Machine Learning Certificate page offers information on a 4-course certificate program for working professionals.",
      "A detailed listing of course descriptions for the AI graduate courses offered as part of the Duke AI program.",
      "A page providing degree details, requirements, and curriculum specifics for Duke's AI Master of Engineering program.",
      "A page showcasing graduate outcomes, career trajectories, and employer data for Duke AI program alumni.",
      "The program overview page for Duke's AI Master of Engineering, highlighting key features and learning objectives.",
      "A general admissions page for Pratt School of Engineering that covers application procedures and requirements across programs.",
      "A comprehensive academics page for Pratt School of Engineering covering undergraduate and graduate offerings.",
      "Duke Continuing Education offers flexible courses and non-degree programs for working professionals.",
      "The Duke Executive Education site features short courses and leadership training for industry professionals.",
      "A portal for Duke Professional Development resources aimed at career advancement and skills enhancement.",
      "An alternate Duke Innovation portal, offering news on technological breakthroughs and startup initiatives.",
      "A Duke Exchange platform that supports student exchanges, internships, and career networking across Duke's community."
  ]


  # Check if URLs are accessible (HTTP status code 200 means accessible)
  aipi_accessible_websites = []
  aipi_accessible_descriptions = []

  for url, desc in zip(aipi_urls, aipi_descriptions):
      try:
          # Use GET request to check status code
          response = requests.get(url, timeout=10)
          if response.status_code == 200:
              aipi_accessible_websites.append(url)
              aipi_accessible_descriptions.append(desc)
          else:
              print(f"[Inaccessible] {url} Status code: {response.status_code}")
      except Exception as e:
          print(f"[Error accessing] {url} Error message: {e}")

  # Output results (only returning the accessible sites)
  print("Accessible URL list:")
  print(aipi_accessible_websites)
  print("\nCorresponding description list:")
  print(aipi_accessible_descriptions)

  import requests

  # List 1: Accessible URLs (only the ones assumed to be publicly accessible)
  pratt_urls = [
      # A. Duke Pratt Internal Pages (from pratt.duke.edu)
      "https://pratt.duke.edu/about/our-story",
      "https://pratt.duke.edu/about/deans-welcome",
      "https://pratt.duke.edu/about/strategic-vision",
      "https://pratt.duke.edu/about/focus-themes",
      "https://pratt.duke.edu/about/history",
      "https://pratt.duke.edu/about/diversity",
      "https://pratt.duke.edu/about/character-forward",
      "https://pratt.duke.edu/about/deans-office",
      "https://pratt.duke.edu/about/board",
      "https://pratt.duke.edu/about/directory",
      "https://pratt.duke.edu/about/careers",
      "https://pratt.duke.edu/about/visit",
      "https://pratt.duke.edu/about/external-faculty-awards",
      "https://pratt.duke.edu/about/nae-members",
      "https://pratt.duke.edu/about/awards",
      "https://pratt.duke.edu/admissions/undergrad",
      "https://pratt.duke.edu/admissions/first-year-design",
      "https://pratt.duke.edu/admissions/outcomes",
      "https://pratt.duke.edu/admissions/masters",
      "https://pratt.duke.edu/admissions/masters-outcomes",
      "https://pratt.duke.edu/admissions/phd",
      "https://pratt.duke.edu/admissions/phd-outcomes",
      "https://pratt.duke.edu/admissions/financial-support",
      "https://pratt.duke.edu/admissions/admitted-students",
      "https://pratt.duke.edu/admissions/international-students",
      "https://pratt.duke.edu/admissions/campus-tours",
      "https://pratt.duke.edu/academics/departments/biomedical",
      "https://pratt.duke.edu/academics/departments/civil-environmental",
      "https://pratt.duke.edu/academics/departments/electrical-computer",
      "https://pratt.duke.edu/academics/departments/mechanical-materials",
      "https://pratt.duke.edu/academics/departments/enterprise-engineering",
      "https://pratt.duke.edu/academics/faculty",
      "https://pratt.duke.edu/academics/undergrad/experience",
      "https://pratt.duke.edu/academics/undergrad/requirements",
      "https://pratt.duke.edu/academics/undergrad/majors-minors",
      "https://pratt.duke.edu/academics/undergrad/4plus1",
      "https://pratt.duke.edu/academics/undergrad/first-year",
      "https://pratt.duke.edu/academics/undergrad/entrepreneurship",
      "https://pratt.duke.edu/academics/undergrad/research",
      "https://pratt.duke.edu/academics/masters/experience",
      "https://pratt.duke.edu/academics/masters/degrees",
      "https://pratt.duke.edu/academics/phd",
      "https://pratt.duke.edu/academics/certificates",
      "https://pratt.duke.edu/life",
      "https://pratt.duke.edu/life/clubs",
      "https://pratt.duke.edu/life/durham",
      "https://pratt.duke.edu/life/resources/undergrad",
      "https://pratt.duke.edu/life/resources/grad",
      "https://pratt.duke.edu/life/resources/advising",
      "https://pratt.duke.edu/life/resources/internships-career",
      "https://pratt.duke.edu/life/resources/phd-plus",
      "https://pratt.duke.edu/life/resources/policies",
      "https://pratt.duke.edu/research/pre-research-support",
      "https://pratt.duke.edu/research/signature-areas",
      "https://pratt.duke.edu/research/external-awards",
      "https://pratt.duke.edu/research/centers",
      "https://pratt.duke.edu/research/signature-discoveries",
      "https://pratt.duke.edu/research/entrepreneurship",
      "https://pratt.duke.edu/research/community",
      "https://pratt.duke.edu/research/2024-report",
      "https://pratt.duke.edu/news",
      "https://pratt.duke.edu/news/media-hits",
      "https://pratt.duke.edu/news/media-relations",
      "https://pratt.duke.edu/news/magazines",
      "https://pratt.duke.edu/news/newsletters",
      "https://pratt.duke.edu/news/podcast",
      "https://pratt.duke.edu/events",
      "https://pratt.duke.edu/events/commencement",
      "https://pratt.duke.edu/events/engineers-week",
      "https://pratt.duke.edu/alumni",
      "https://pratt.duke.edu/parents",
      "https://pratt.duke.edu/giving",
      "https://pratt.duke.edu/industry",
      "https://pratt.duke.edu/industry/student",
      "https://pratt.duke.edu/industry/affiliates",
      "https://pratt.duke.edu/apply",
      "https://www.facebook.com/DukeEngineering",
      "https://www.instagram.com/dukeengineering",
      "https://www.youtube.com/c/DukeEngineering",
      "https://www.linkedin.com/school/duke-engineering/",
      "https://pratt.duke.edu/contact",
      # Below are pages hosted on external domains but closely affiliated with Duke
      "https://web.accessibility.duke.edu",
      "https://form.asana.com/form/web-problem",
      "https://oarc.duke.edu",
      # B. Related Duke and Departmental Websites
      "https://bme.duke.edu/",
      "https://cee.duke.edu/",
      "https://ece.duke.edu/",
      "https://mems.duke.edu/",
      "https://pratt.duke.edu/academics/departments/enterprise-engineering",  # also for enterprise
      "https://research.duke.edu/",
      "https://www.duke.edu/",
      "https://admissions.duke.edu/",
      "https://dukekunshan.edu.cn/",
      "https://nasher.duke.edu/",
      "https://library.duke.edu/",
      "https://alumni.duke.edu/",
      "https://goduke.com/",
      "https://www.dukehealth.org/",
      "https://innovation.duke.edu/",
      "https://globalhealth.duke.edu/",
      "https://divinity.duke.edu/",
      "https://www.fuqua.duke.edu/",
      "https://sanford.duke.edu/",
      "https://law.duke.edu/",
      "https://medschool.duke.edu/",
      "https://www.cs.duke.edu/",
      "https://math.duke.edu/",
      "https://twitter.com/dukeengineering",
      "https://studentaffairs.duke.edu/career",
      "https://sustainability.duke.edu/",
      "https://www.dukechronicle.com/",
      "https://dukemagazine.duke.edu/",
      "https://studentaffairs.duke.edu/",
      "https://sustainability.duke.edu/initiatives",
      "https://today.duke.edu/"
  ]

  # List 2: Corresponding English Descriptions
  pratt_descriptions = [
      # A. Duke Pratt Internal Pages
      "The history and narrative that explains the legacy and mission of Duke's Pratt School of Engineering.",
      "A personal welcome message and overview from the dean outlining the school's vision.",
      "Details on the long-term goals and strategic initiatives of the school.",
      "Highlights the key research and educational themes driving innovation at Pratt.",
      "An in-depth timeline covering the evolution and milestones of the school.",
      "Outlines Pratt's commitment to diversity, equity, and building an inclusive community.",
      "Showcases the school's emphasis on character, integrity, and ethics in education.",
      "Introduces the dean's office staff who support the leadership of the school.",
      "Provides information about the advisory board of visitors that support the school's direction.",
      "A searchable directory of faculty, staff, and key contacts at Pratt.",
      "Lists job opportunities and career resources available at the school.",
      "Details for prospective visitors including campus tour information.",
      "Highlights honors and awards received by Pratt faculty from external organizations.",
      "Lists Pratt affiliates and alumni who have been elected to the National Academy of Engineering.",
      "Summarizes awards and recognitions that are specific to the school.",
      "Resources for prospective undergraduate applicants, including requirements and tips.",
      "Describes the innovative first-year design program emphasizing real-life problem solving.",
      "Data and success stories showcasing the outcomes for undergraduate students.",
      "Detailed application process and information for prospective master's degree applicants.",
      "Outcome data and success stories for master's program graduates.",
      "Application details, criteria, and research opportunities for PhD candidates.",
      "Career trajectories and achievements of PhD graduates from Pratt.",
      "Information on scholarships, grants, and financial aid options for students.",
      "Guidance and resources for applicants who have been admitted to the program.",
      "Support and application resources targeted at international students.",
      "Information on scheduling and participating in campus tours.",
      "Overview of the Biomedical Engineering department's academic and research offerings.",
      "Details on the Civil & Environmental Engineering department's programs and research focus.",
      "Information on the Electrical & Computer Engineering department, highlighting digital systems and innovations.",
      "Overview of the Mechanical Engineering & Materials Science department's programs and research breakthroughs.",
      "Showcases interdisciplinary programs that merge technical expertise with entrepreneurship.",
      "A complete directory of academic leaders and research faculty at Pratt.",
      "Describes the comprehensive educational experience of undergraduate students.",
      "Outlines the degree and graduation requirements for Pratt undergraduate programs.",
      "Details the available majors, minors, and interdisciplinary options within engineering.",
      "Explains the combined bachelor's and master's degree program (4+1).",
      "Focuses on the orientation and initial student experiences during the first year.",
      "Highlights student initiatives and opportunities in entrepreneurship.",
      "Provides details about undergraduate research opportunities at Pratt.",
      "Describes the immersive learning environment in master's programs.",
      "Summarizes the various master's degree options available at the school.",
      "Information on the doctoral programs, research requirements, and career paths for PhD candidates.",
      "Explores available professional and interdisciplinary certificate options.",
      "Features student life, extracurricular activities, and community events at Pratt.",
      "Lists student organizations, clubs, and teams enhancing campus life.",
      "Provides insights into living in Durham and how it enriches the student experience.",
      "A one-stop page for academic support, counseling, and other resources for undergraduates.",
      "Support services, professional development, and resources for graduate students.",
      "Information on academic advising and mentoring programs at Pratt.",
      "Connects students with internship opportunities and career planning support.",
      "Specialized resources for the professional development of doctoral students.",
      "Detailed academic policies and procedures for undergraduate students.",
      "Resources and support to help students initiate and fund research projects.",
      "Highlights the school's key research themes and areas of innovation.",
      "Showcases major external research awards and grants received by Pratt teams.",
      "Lists research centers and institutes that foster interdisciplinary collaboration.",
      "Celebrates significant innovations and discoveries developed at Pratt.",
      "Overview of research initiatives that have led to startup ventures and technology transfer.",
      "Explains how Pratt engages with local and global communities to solve real-world problems.",
      "The comprehensive impact report detailing research achievements and funding statistics for 2024.",
      "Aggregates the latest news, press releases, and updates from Pratt School.",
      "A collection of media stories and press coverage featuring Pratt's accomplishments.",
      "Contact and information page for media inquiries related to Pratt.",
      "Digital and printed magazines produced by or featuring the work of the Pratt community.",
      "Subscription page for regular email newsletters and news updates.",
      "A podcast series with interviews and discussions on breakthrough engineering ideas.",
      "A calendar of upcoming events, seminars, and public lectures hosted by the school.",
      "Details and highlights of the commencement and graduation ceremonies at Pratt.",
      "Information on Engineers Week events that feature workshops, talks, and networking sessions.",
      "Dedicated resources and news for Pratt alumni to stay engaged with the community.",
      "Information and resources specifically for the parents of current and prospective students.",
      "Opportunities and information on donating to support Pratt's initiatives.",
      "Connects industry partners with academic research and innovation at Pratt.",
      "Highlights programs that involve students in industry projects and real-world work.",
      "A platform for companies and organizations to affiliate with Pratt.",
      "The central starting point for prospective students beginning the application process.",
      "Pratt's official Facebook page, featuring campus updates and success stories.",
      "The official Instagram account showing visual snapshots and behind-the-scenes at Pratt.",
      "The official YouTube channel with videos on research highlights and student experiences.",
      "A LinkedIn page showcasing career opportunities and professional news for Pratt.",
      "A contact page with inquiry forms and directions to the Pratt School.",
      "A dedicated page outlining Duke's accessibility features and inclusive design resources.",
      "A form for reporting website issues or technical problems on the Pratt site.",
      "Details about Duke's data usage, cookies, and privacy policies.",
      # B. Related Duke and Departmental Websites
      "The official website for Duke's Biomedical Engineering program with academic and research information.",
      "Showcases Duke Civil & Environmental Engineering programs and sustainability projects.",
      "Highlights advanced topics and research in Duke Electrical & Computer Engineering.",
      "Details academic programs and breakthroughs in Duke Mechanical Engineering & Materials Science.",
      "Focuses on interdisciplinary enterprise engineering combining technical skills with entrepreneurship.",
      "The central portal for research initiatives and interdisciplinary projects at Duke University.",
      "The main website for Duke University, providing overall information on academics and campus life.",
      "The official admissions site for Duke University's undergraduate programs.",
      "Duke Kunshan University provides an international, interdisciplinary educational experience.",
      "The official site for the Nasher Museum of Art featuring exhibitions and cultural events.",
      "Duke University Libraries offers research resources and academic support services.",
      "The Duke Alumni site for networking, events, and career services post-graduation.",
      "The official athletics site for Duke University's Blue Devils sports teams.",
      "Information on Duke University Health System's clinical and research initiatives.",
      "A portal to support startups and entrepreneurial initiatives stemming from Duke's research.",
      "Showcases Duke Global Health Institute's interdisciplinary research on global health issues.",
      "The official website for Duke Divinity School, featuring academic programs and community outreach.",
      "Provides information about Duke Fuqua School of Business and its MBA and executive programs.",
      "Offers details on public policy programs and research addressing national and global issues.",
      "The official website for Duke Law School with academic programs and legal research.",
      "Comprehensive information on Duke University School of Medicine's education and training.",
      "Highlights research and academic programs in Duke's Computer Science Department.",
      "Details academic programs and research opportunities in Duke's Mathematics Department.",
      "The official Twitter account for Duke Engineering, sharing real-time news and updates.",
      "Provides career services, internships, and job placement resources for Duke students.",
      "Features Duke's sustainability initiatives and green technology projects.",
      "An internal resource on research administration and interdisciplinary projects at Duke.",
      "The independent student-run newspaper reporting on campus news at Duke.",
      "A publication that highlights achievements and breakthrough stories from Duke's community.",
      "Provides campus services, programming, and support for student life at Duke.",
      "Details specific projects and programs focused on sustainability at Duke.",
      "The official Duke research news site with updates on breakthroughs and campus discoveries."
  ]


  # Check if URLs are accessible (HTTP status code 200 means accessible)
  pratt_accessible_websites = []
  pratt_accessible_descriptions = []

  for url, desc in zip(pratt_urls, pratt_descriptions):
      try:
          # Use GET request to check status code
          response = requests.get(url, timeout=10)
          if response.status_code == 200:
              pratt_accessible_websites.append(url)
              pratt_accessible_descriptions.append(desc)
          else:
              print(f"[Inaccessible] {url} Status code: {response.status_code}")
      except Exception as e:
          print(f"[Error accessing] {url} Error message: {e}")

  # Output results (only returning the accessible sites)
  print("Accessible URL list:")
  print(pratt_accessible_websites)
  print("\nCorresponding description list:")
  print(pratt_accessible_descriptions)


  all_urls = duke_websites + aipi_accessible_websites + pratt_accessible_websites
  chunks = duke_descriptions + aipi_descriptions + pratt_descriptions

  return all_urls, chunks
